print("BANO_QABIL CALCULATOR")
print("")
print("")
print("_Calculator for \"ADDITION\"_")
x=int(input("Enter First Number:"))
y=int(input("Enter Second Number:"))
z= x+y
print(f"Your answer is:\"{z}\"")
print("")
print("_Calculator for \"SUBTRACTION\"_")
x=int(input("Enter First Number:"))
y=int(input("Enter Second Number:"))
z= x-y
print(f"Your answer is:\"{z}\"")
print("")
print("_Calculator for \"MULTIPLICATION\"_")
x=int(input("Enter First Number:"))
y=int(input("Enter Second Number:"))
z= x*y
print(f"Your answer is:\"{z}\"")
print("")
print("_Calculator for \"DIVISION\"_")
x=int(input("Enter First Number:"))
y=int(input("Enter Second Number:"))
z= x/y
print(f"Your answer is:\"{z}\"")
print("")
